### ISSUE TITLE
Is there a demo to detect the human action?

### ISSUE THREAD

**Issue by MILOTIDE** [vra/action-recognition-using-3d-resnet#1]
Hi, i find the main.py only provide the accuracy of the net, is there a demo that can detect the human action in a short video?Thanks.

**Comment by vra** [comment]
Hi @MILOTIDE ,
Thanks for your interest. However, in the task of action recognition, there are usually don't have a action detection procedure. If you want to show the results of action recognition, you can use a human body detection program.
