### ISSUE TITLE
can you give a corresponding list about the HMDB51 data's original with the index you rename?

### ISSUE THREAD

**Issue by hugddygff** [vra/action-recognition-using-3d-resnet#2]
thanks very much!

**Comment by vra** [comment]
Hi @hugddygff,
Thanks for your interest, I just uploaded two files named {train, val}_old_to_new.txt in `data/lists/hmdb51`  directory. The format of each line is
```bash
origin-video-name video-class/renamed-video-name
```
for example:
```bash
Aussie_Brunette_Brushing_Hair_II_brush_hair_u_nm_np1_ri_med_3 brush_hair/000004
```

**Comment by hugddygff** [comment]
@vra Thanks again for your quick reply!
