### ISSUE TITLE
why your old_to_new_list is different to official test_train_splits?

### ISSUE THREAD

**Issue by Rainlolthx** [vra/action-recognition-using-3d-resnet#3]
brush_hair in your list has 130 records, but there is only 107 videos

**Comment by vra** [comment]
Hi, @Rainlolthx,
Thanks for your attention. Sorry for the mistake. I did these experiments a long time ago, some data may be missing. But the main framework can be useful, you can create your own list then run the other part of code.

**Comment by Rainlolthx** [comment]
Thanks for your reply
