### ISSUE TITLE
C3D features

### ISSUE THREAD

**Issue by ghost** [vra/action-recognition-using-3d-resnet#5]
Hi,

C3D features provided on google drive are incomplete for UCF101, as C3D features of HandstandPushups action is missing in computed c3D feature.

please help

**Comment by vra** [comment]
Hi @MyWorldN ,
Please search `HandStandPushups`

**Comment by ghost** [comment]
I have searched it, these c3D features of HandstandPushups videos are not present in json file. Please help me. Just provide me c3D features of HandstandPushups.

**Comment by imvidit** [comment]
hi, please provide the precomputed features for UCF101.
